"""
Script simple de diagnóstico sin dependencias externas
"""

from datetime import datetime

print("="*60)
print("DIAGNÓSTICO: Fuel Reset on Login")
print("="*60)
print(f"Hora actual: {datetime.now()}")
print("="*60)
print()

print("PROBLEMA:")
print("Los litros se resetean cada vez que el cliente hace login")
print()

print("CAUSA MÁS PROBABLE:")
print("La columna 'fecha_ultimo_reset' en la tabla 'sistema_config'")
print("está en NULL o no se está actualizando correctamente.")
print()

print("="*60)
print("SOLUCIÓN INMEDIATA")
print("="*60)
print()
print("Ejecuta este SQL en tu base de datos de producción:")
print()
print("UPDATE sistema_config")
print("SET fecha_ultimo_reset = CURRENT_DATE")
print("WHERE id = 1;")
print()
print("Esto establecerá la fecha de último reset a HOY,")
print("evitando que se resetee en cada login.")
print()

print("="*60)
print("VERIFICACIÓN")
print("="*60)
print()
print("Después de ejecutar el SQL:")
print("1. Haz login con un cliente")
print("2. Verifica que los litros NO se reseteen")
print("3. Haz login nuevamente")
print("4. Los litros deben permanecer iguales")
print()

print("="*60)
print("¿DÓNDE EJECUTAR EL SQL?")
print("="*60)
print()
print("Si usas Railway:")
print("  1. Ve a tu proyecto en Railway")
print("  2. Click en tu base de datos PostgreSQL")
print("  3. Ve a la pestaña 'Data'")
print("  4. Ejecuta el SQL ahí")
print()
print("Si usas Render:")
print("  1. Ve a tu dashboard de Render")
print("  2. Click en tu base de datos PostgreSQL")
print("  3. Click en 'Connect' → 'External Connection'")
print("  4. Usa un cliente como pgAdmin o DBeaver")
print("  5. Ejecuta el SQL")
print()
